services: 
  db:
    container_name: rise_database_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  # # API services
  api: 
    image: rise
    ports: 
      - 3300:3300
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: 'development'
      DEV_PORT: 3300
      DATABASE_DEV_STRING: 'postgres://postgres:@rise_database_container:5432/rise-dev-db'
      DEV_PAPERTRAIL_HOST: 'logs4.papertrailapp.com'
      DEV_PAPERTRAIL_PORT: 36518
      JWT_SECRET: 'somerandomekeynumberalpha'
    depends_on: 
      - db
